"""empty message

Revision ID: f91700535c38
Revises: 94af7107bf12
Create Date: 2025-11-25 16:29:57.963674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91700535c38'
down_revision: Union[str, Sequence[str], None] = '94af7107bf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventories_product_id_key'), 'inventories', type_='unique')
    op.drop_constraint(op.f('inventories_user_id_key'), 'inventories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('inventories_user_id_key'), 'inventories', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('inventories_product_id_key'), 'inventories', ['product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
